### ISSUE TITLE
Nefunkční odesílání SMS v detailu objednávky

### ISSUE THREAD

**Issue by JaKopecky** [BulkGate/prestasms#8]
V detailu objednávky  je panel PRESTASMS prázdny. Při načítání se zobrazuje text "Loading content", který po chvilce zmizí.

V konzoli prohlížeče je toto chybové hlášení:

Chyba zdrojové mapy: Error: NetworkError when attempting to fetch resource.
URL adresa zdroje: https://portal.bulkgate.com/dist/react/module-components_send-sms.bundle.js?hash=******************************
URL adresa zdrojové mapy: module-components_send-sms.bundle.js.map

PrestaShop 1.6.1.24

**Comment by MartinKreizl** [comment]
Dobrý den. Problém by již měl být vyřešen. Děkujeme za Váš feedback.
